biji_user_index:
    path:     /index
    defaults: { _controller: BIJIUserBundle:User:index }

biji_user_add:
    path:     /add
    defaults: { _controller: BIJIUserBundle:User:add }

biji_user_create:
    path:     /create
    defaults: { _controller: BIJIUserBundle:User:create }
    methods: POST

biji_user_edit:
    path:     /edit/{id}
    defaults: { _controller: BIJIUserBundle:User:edit }

biji_user_update:
    path:     /update/{id}
    defaults: { _controller: BIJIUserBundle:User:update }
    methods: [POST, PUT]

biji_user_view:
    path:     /view/{id}
    defaults: { _controller: BIJIUserBundle:User:view }

biji_user_delete:
    path:     /delete/{id}
    defaults: { _controller: BIJIUserBundle:User:delete }
    methods: [POST, DELETE]

biji_user_redirect_add:
    path:     /create
    defaults:
           _controller: BIJIUserBundle:User:add
           permanent: true

biji_user_redirect_edit:
    path:     /update/{id}
    defaults:
           _controller: BIJIUserBundle:User:edit
           path:     /user/edit/{id}
           permanent: true