biji_user_user:
    resource: "@BIJIUserBundle/Resources/config/routes/user.yml"
    prefix:   /user

biji_task_task:
    resource: "@BIJIUserBundle/Resources/config/routes/task.yml"
    prefix: /task

# Autentication

biji_user_homepage:
    path:     /
    defaults: { _controller: BIJIUserBundle:User:home }

biji_user_login:
    path:     /login
    defaults: { _controller: BIJIUserBundle:Security:login }

biji_user_login_check:
    path:     /login_check
    defaults: { _controller: BIJIUserBundle:Security:loginCheck }

biji_user_logout:
    path: /logout